"""
Kitchen Pick & Place Environment Configuration
Generated by BlueprintRecipe

This file defines the environment configuration for Isaac Lab.
"""

from dataclasses import MISSING
from typing import Literal

import omni.isaac.lab.sim as sim_utils
from omni.isaac.lab.assets import ArticulationCfg, AssetBaseCfg, RigidObjectCfg
from omni.isaac.lab.envs import ManagerBasedEnvCfg
from omni.isaac.lab.managers import EventTermCfg, ObservationGroupCfg, ObservationTermCfg
from omni.isaac.lab.managers import RewardTermCfg, SceneEntityCfg, TerminationTermCfg
from omni.isaac.lab.scene import InteractiveSceneCfg
from omni.isaac.lab.utils import configclass


@configclass
class KitchenSceneCfg(InteractiveSceneCfg):
    """Configuration for the kitchen scene."""

    # Ground plane
    ground = AssetBaseCfg(
        prim_path="/World/ground",
        spawn=sim_utils.GroundPlaneCfg(),
    )

    # Kitchen scene USD
    kitchen_scene = AssetBaseCfg(
        prim_path="/World/Kitchen",
        spawn=sim_utils.UsdFileCfg(
            usd_path="../scene.usda",
            scale=(1.0, 1.0, 1.0),
        ),
    )

    # Robot (Franka Panda)
    robot = ArticulationCfg(
        prim_path="/World/Robot",
        spawn=sim_utils.UsdFileCfg(
            usd_path="omniverse://localhost/NVIDIA/Assets/Isaac/2023.1.1/Isaac/Robots/Franka/franka_instanceable.usd",
            activate_contact_sensors=True,
        ),
        init_state=ArticulationCfg.InitialStateCfg(
            pos=(0.0, 0.0, 0.0),
            joint_pos={
                "panda_joint1": 0.0,
                "panda_joint2": -0.785,
                "panda_joint3": 0.0,
                "panda_joint4": -2.356,
                "panda_joint5": 0.0,
                "panda_joint6": 1.571,
                "panda_joint7": 0.785,
                "panda_finger_joint1": 0.04,
                "panda_finger_joint2": 0.04,
            },
        ),
    )

    # Target object (mug) - will be randomized
    target_object = RigidObjectCfg(
        prim_path="/World/Kitchen/Objects/mug_01",
        spawn=None,  # Already in scene
        init_state=RigidObjectCfg.InitialStateCfg(),
    )

    # Lighting
    light = AssetBaseCfg(
        prim_path="/World/Light",
        spawn=sim_utils.DomeLightCfg(
            intensity=1500.0,
            color=(1.0, 1.0, 1.0),
        ),
    )


@configclass
class ObservationsCfg:
    """Observation configuration."""

    @configclass
    class PolicyCfg(ObservationGroupCfg):
        """Observations for the policy."""

        # Robot state
        joint_pos = ObservationTermCfg(
            func="omni.isaac.lab.envs.mdp.joint_pos",
            params={"asset_cfg": SceneEntityCfg("robot")},
        )
        joint_vel = ObservationTermCfg(
            func="omni.isaac.lab.envs.mdp.joint_vel",
            params={"asset_cfg": SceneEntityCfg("robot")},
        )

        # End-effector state
        ee_pos = ObservationTermCfg(
            func="omni.isaac.lab.envs.mdp.body_pos_w",
            params={
                "asset_cfg": SceneEntityCfg("robot"),
                "body_name": "panda_hand"
            },
        )

        # Target object state
        target_pos = ObservationTermCfg(
            func="omni.isaac.lab.envs.mdp.root_pos_w",
            params={"asset_cfg": SceneEntityCfg("target_object")},
        )

        def __post_init__(self):
            self.enable_corruption = False
            self.concatenate_terms = True

    policy: PolicyCfg = PolicyCfg()


@configclass
class ActionsCfg:
    """Action configuration."""

    joint_vel = {
        "class_type": "omni.isaac.lab.envs.mdp.JointVelocityActionCfg",
        "asset_name": "robot",
        "joint_names": [".*"],
        "scale": 0.1,
    }


@configclass
class RewardsCfg:
    """Reward configuration."""

    # Distance to target
    reaching = RewardTermCfg(
        func="reward_reaching",
        weight=1.0,
    )

    # Grasp success
    grasp_success = RewardTermCfg(
        func="reward_grasp_success",
        weight=10.0,
    )

    # Collision penalty
    collision = RewardTermCfg(
        func="reward_collision_penalty",
        weight=-1.0,
    )

    # Smooth motion
    smooth_motion = RewardTermCfg(
        func="reward_smooth_motion",
        weight=-0.01,
    )


@configclass
class TerminationsCfg:
    """Termination configuration."""

    time_out = TerminationTermCfg(
        func="omni.isaac.lab.envs.mdp.time_out",
        time_out=True,
    )

    object_dropped = TerminationTermCfg(
        func="termination_object_dropped",
        params={"threshold": -0.1},
    )


@configclass
class EventsCfg:
    """Event configuration for domain randomization."""

    # Reset object position
    reset_object = EventTermCfg(
        func="randomize_object_pose",
        mode="reset",
        params={
            "position_range": (-0.3, 0.3, -0.3, 0.3, 0.9, 1.0),
        },
    )

    # Randomize lighting
    randomize_lighting = EventTermCfg(
        func="randomize_lighting",
        mode="reset",
        params={
            "intensity_range": (500.0, 2000.0),
        },
    )


@configclass
class KitchenPickPlaceEnvCfg(ManagerBasedEnvCfg):
    """Configuration for kitchen pick and place environment."""

    # Scene
    scene: KitchenSceneCfg = KitchenSceneCfg(num_envs=1024, env_spacing=3.0)

    # Basic settings
    observations: ObservationsCfg = ObservationsCfg()
    actions: ActionsCfg = ActionsCfg()
    rewards: RewardsCfg = RewardsCfg()
    terminations: TerminationsCfg = TerminationsCfg()
    events: EventsCfg = EventsCfg()

    # Episode settings
    episode_length_s = 10.0  # seconds

    def __post_init__(self):
        """Post initialization."""
        self.sim.dt = 1.0 / 60.0
        self.sim.render_interval = 1
        self.scene.num_envs = 1024
